
name: Workflow com horário

on:
  schedule:
    - cron: '16 16 * * *'
    - cron: '0 0 1 * *' 
  workflow_dispatch:
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Não na segunda ou quarta  #Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Não se for manual
        if:  ${{ github.event_name != 'workflow_dispatch' }}
        run: echo "Esse evento vai ser pulado na execução manual"
      - name: Every time
        run: echo "This step will always run"
        
        
